server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jpadb?characterEncoding=utf8
    username: jpauser
    password: 111111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        default_batch_fetch_size: 500
    database: mysql
  data:
    redis:
      host: localhost
      port: 6379
      password: aaaa
  springdoc:
    swagger-ui:
      tags-sorter: method
      display-request-duration: true
    api-docs:
      path: /api-docs/json
      groups:
        enabled: true
    cache:
      disabled: true
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
jwt:
#  expiration_time: 1800000 # 30 * 60 * 1000 30m
#  refresh_expiration_time: 604800000 # 7 * 24 * 60 * 60 * 1000L 7d
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa